insert into public.categories(name,slug) values
 ('Alimentação e Bebidas','alimentacao-e-bebidas'),
 ('Saúde','saude'),
 ('Beleza e Estética','beleza-e-estetica'),
 ('Automóveis e Motos','automoveis-e-motos'),
 ('Tecnologia e Eletrônicos','tecnologia-e-eletronicos'),
 ('Casa e Construção','casa-e-construcao'),
 ('Comércio e Lojas','comercio-e-lojas'),
 ('Educação','educacao'),
 ('Serviços Profissionais','servicos-profissionais'),
 ('Serviços Domésticos','servicos-domesticos'),
 ('Imóveis','imoveis'),
 ('Turismo e Hospedagem','turismo-e-hospedagem'),
 ('Esporte e Fitness','esporte-e-fitness'),
 ('Pet','pet'),
 ('Eventos e Festas','eventos-e-festas'),
 ('Moda e Vestuário','moda-e-vestuario'),
 ('Financeiro','financeiro'),
 ('Transporte e Logística','transporte-e-logistica'),
 ('Agronegócio e Rural','agronegocio-e-rural'),
 ('Indústria e Empresas','industria-e-empresas'),
 ('Segurança','seguranca'),
 ('Religião e Comunidade','religiao-e-comunidade'),
 ('Entretenimento e Lazer','entretenimento-e-lazer'),
 ('Comunicação e Marketing','comunicacao-e-marketing'),
 ('Serviços Públicos e Utilidades','servicos-publicos-e-utilidades'),
 ('Empregos e Recursos Humanos','empregos-e-recursos-humanos'),
 ('Seguros e Proteção','seguros-e-protecao'),
 ('Música e Cultura','musica-e-cultura'),
 ('Infantil','infantil'),
 ('Serviços para Empresas','servicos-para-empresas'),
 ('Compras e Atacado','compras-e-atacado')
 on conflict(slug) do nothing;
